import { UserRole, LessonStatus } from '@ilona/database';
import { CreateLessonDto, UpdateLessonDto, CompleteLessonDto } from './dto';
import { LessonCrudService } from './lesson-crud.service';
import { LessonStatusService } from './lesson-status.service';
import { LessonActionsService } from './lesson-actions.service';
import { LessonSchedulingService } from './lesson-scheduling.service';
import { LessonStatisticsService } from './lesson-statistics.service';
export declare class LessonsService {
    private readonly crudService;
    private readonly statusService;
    private readonly actionsService;
    private readonly schedulingService;
    private readonly statisticsService;
    constructor(crudService: LessonCrudService, statusService: LessonStatusService, actionsService: LessonActionsService, schedulingService: LessonSchedulingService, statisticsService: LessonStatisticsService);
    findAll(params?: {
        skip?: number;
        take?: number;
        centerId?: string;
        groupId?: string;
        groupIds?: string[];
        teacherId?: string;
        teacherIds?: string[];
        status?: LessonStatus;
        dateFrom?: Date;
        dateTo?: Date;
        sortBy?: string;
        sortOrder?: 'asc' | 'desc';
        search?: string;
        currentUserId?: string;
        userRole?: UserRole;
    }): Promise<unknown>;
    findById(id: string, currentUserId?: string, userRole?: UserRole): Promise<unknown>;
    findByTeacher(teacherId: string, dateFrom?: Date, dateTo?: Date): Promise<unknown>;
    getTodayLessons(teacherId: string): Promise<unknown>;
    getUpcoming(teacherId: string, limit?: number): Promise<({
        group: {
            name: string;
            id: string;
            _count: {
                students: number;
            };
            level: string | null;
        };
    } & {
        status: import("@ilona/database").$Enums.LessonStatus;
        groupId: string;
        teacherId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        duration: number;
        description: string | null;
        topic: string | null;
        creationSource: import("@ilona/database").$Enums.LessonCreationSource;
        substituteTeacherId: string | null;
        scheduledAt: Date;
        vocabularySent: boolean;
        vocabularySentAt: Date | null;
        feedbacksCompleted: boolean;
        feedbacksCompletedAt: Date | null;
        absenceMarked: boolean;
        absenceMarkedAt: Date | null;
        voiceSent: boolean;
        voiceSentAt: Date | null;
        textSent: boolean;
        textSentAt: Date | null;
        completedAt: Date | null;
    })[]>;
    create(dto: CreateLessonDto, currentUserId?: string, userRole?: UserRole): Promise<unknown>;
    createBulk(lessons: CreateLessonDto[], currentUserId?: string, userRole?: UserRole): Promise<unknown>;
    update(id: string, dto: UpdateLessonDto, userId?: string, userRole?: UserRole): Promise<{
        group: {
            name: string;
            centerId: string;
            id: string;
        };
        teacher: {
            user: {
                id: string;
                firstName: string;
                lastName: string;
            };
        } & {
            id: string;
            userId: string;
            createdAt: Date;
            updatedAt: Date;
            bio: string | null;
            specialization: string | null;
            hourlyRate: import("@ilona/database/dist/generated/client/runtime/library").Decimal;
            lessonRateAMD: import("@ilona/database/dist/generated/client/runtime/library").Decimal | null;
            videoUrl: string | null;
            workingDays: string[];
            workingHours: import("@ilona/database/dist/generated/client/runtime/library").JsonValue | null;
            hireDate: Date | null;
        };
        dailyPlan: {
            id: string;
            createdAt: Date;
        } | null;
        substituteTeacher: ({
            user: {
                id: string;
                firstName: string;
                lastName: string;
            };
        } & {
            id: string;
            userId: string;
            createdAt: Date;
            updatedAt: Date;
            bio: string | null;
            specialization: string | null;
            hourlyRate: import("@ilona/database/dist/generated/client/runtime/library").Decimal;
            lessonRateAMD: import("@ilona/database/dist/generated/client/runtime/library").Decimal | null;
            videoUrl: string | null;
            workingDays: string[];
            workingHours: import("@ilona/database/dist/generated/client/runtime/library").JsonValue | null;
            hireDate: Date | null;
        }) | null;
    } & {
        status: import("@ilona/database").$Enums.LessonStatus;
        groupId: string;
        teacherId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        duration: number;
        description: string | null;
        topic: string | null;
        creationSource: import("@ilona/database").$Enums.LessonCreationSource;
        substituteTeacherId: string | null;
        scheduledAt: Date;
        vocabularySent: boolean;
        vocabularySentAt: Date | null;
        feedbacksCompleted: boolean;
        feedbacksCompletedAt: Date | null;
        absenceMarked: boolean;
        absenceMarkedAt: Date | null;
        voiceSent: boolean;
        voiceSentAt: Date | null;
        textSent: boolean;
        textSentAt: Date | null;
        completedAt: Date | null;
    } & {
        isLockedForTeacher: boolean;
        completionStatus: "DONE" | "IN_PROCESS" | null;
        dailyDutiesStatus: import("@ilona/types").DailyDutiesLessonStatus;
        dailyPlanCompleted: boolean;
        isAbsenceLocked: boolean;
        isFeedbackLocked: boolean;
        isVoiceLocked: boolean;
        isTextLocked: boolean;
        isDailyPlanLocked: boolean;
        dutyActionStatus: {
            absence: import("@ilona/types").DutyActionStatus;
            feedback: import("@ilona/types").DutyActionStatus;
            voice: import("@ilona/types").DutyActionStatus;
            text: import("@ilona/types").DutyActionStatus;
            dailyPlan: import("@ilona/types").DutyActionStatus;
        };
    }>;
    setSubstituteForGroupDay(params: {
        groupId: string;
        date: string;
        substituteTeacherId: string | null;
    }, userId?: string, userRole?: UserRole): Promise<unknown>;
    delete(id: string): Promise<{
        status: import("@ilona/database").$Enums.LessonStatus;
        groupId: string;
        teacherId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        duration: number;
        description: string | null;
        topic: string | null;
        creationSource: import("@ilona/database").$Enums.LessonCreationSource;
        substituteTeacherId: string | null;
        scheduledAt: Date;
        vocabularySent: boolean;
        vocabularySentAt: Date | null;
        feedbacksCompleted: boolean;
        feedbacksCompletedAt: Date | null;
        absenceMarked: boolean;
        absenceMarkedAt: Date | null;
        voiceSent: boolean;
        voiceSentAt: Date | null;
        textSent: boolean;
        textSentAt: Date | null;
        completedAt: Date | null;
    }>;
    deleteBulk(lessonIds: string[], currentUserId?: string, userRole?: UserRole): Promise<{
        success: boolean;
        deletedCount: number;
    }>;
    startLesson(id: string, userId: string, userRole: UserRole): Promise<{
        status: import("@ilona/database").$Enums.LessonStatus;
        groupId: string;
        teacherId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        duration: number;
        description: string | null;
        topic: string | null;
        creationSource: import("@ilona/database").$Enums.LessonCreationSource;
        substituteTeacherId: string | null;
        scheduledAt: Date;
        vocabularySent: boolean;
        vocabularySentAt: Date | null;
        feedbacksCompleted: boolean;
        feedbacksCompletedAt: Date | null;
        absenceMarked: boolean;
        absenceMarkedAt: Date | null;
        voiceSent: boolean;
        voiceSentAt: Date | null;
        textSent: boolean;
        textSentAt: Date | null;
        completedAt: Date | null;
    }>;
    completeLesson(id: string, dto: CompleteLessonDto, userId: string, userRole: UserRole): Promise<unknown>;
    cancelLesson(id: string, reason?: string, userId?: string, userRole?: UserRole): Promise<{
        status: import("@ilona/database").$Enums.LessonStatus;
        groupId: string;
        teacherId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        duration: number;
        description: string | null;
        topic: string | null;
        creationSource: import("@ilona/database").$Enums.LessonCreationSource;
        substituteTeacherId: string | null;
        scheduledAt: Date;
        vocabularySent: boolean;
        vocabularySentAt: Date | null;
        feedbacksCompleted: boolean;
        feedbacksCompletedAt: Date | null;
        absenceMarked: boolean;
        absenceMarkedAt: Date | null;
        voiceSent: boolean;
        voiceSentAt: Date | null;
        textSent: boolean;
        textSentAt: Date | null;
        completedAt: Date | null;
    }>;
    markMissed(id: string): Promise<{
        status: import("@ilona/database").$Enums.LessonStatus;
        groupId: string;
        teacherId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        duration: number;
        description: string | null;
        topic: string | null;
        creationSource: import("@ilona/database").$Enums.LessonCreationSource;
        substituteTeacherId: string | null;
        scheduledAt: Date;
        vocabularySent: boolean;
        vocabularySentAt: Date | null;
        feedbacksCompleted: boolean;
        feedbacksCompletedAt: Date | null;
        absenceMarked: boolean;
        absenceMarkedAt: Date | null;
        voiceSent: boolean;
        voiceSentAt: Date | null;
        textSent: boolean;
        textSentAt: Date | null;
        completedAt: Date | null;
    }>;
    markVocabularySent(id: string): Promise<{
        status: import("@ilona/database").$Enums.LessonStatus;
        groupId: string;
        teacherId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        duration: number;
        description: string | null;
        topic: string | null;
        creationSource: import("@ilona/database").$Enums.LessonCreationSource;
        substituteTeacherId: string | null;
        scheduledAt: Date;
        vocabularySent: boolean;
        vocabularySentAt: Date | null;
        feedbacksCompleted: boolean;
        feedbacksCompletedAt: Date | null;
        absenceMarked: boolean;
        absenceMarkedAt: Date | null;
        voiceSent: boolean;
        voiceSentAt: Date | null;
        textSent: boolean;
        textSentAt: Date | null;
        completedAt: Date | null;
    }>;
    markAbsenceComplete(id: string, userId?: string, userRole?: UserRole): Promise<{
        status: import("@ilona/database").$Enums.LessonStatus;
        groupId: string;
        teacherId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        duration: number;
        description: string | null;
        topic: string | null;
        creationSource: import("@ilona/database").$Enums.LessonCreationSource;
        substituteTeacherId: string | null;
        scheduledAt: Date;
        vocabularySent: boolean;
        vocabularySentAt: Date | null;
        feedbacksCompleted: boolean;
        feedbacksCompletedAt: Date | null;
        absenceMarked: boolean;
        absenceMarkedAt: Date | null;
        voiceSent: boolean;
        voiceSentAt: Date | null;
        textSent: boolean;
        textSentAt: Date | null;
        completedAt: Date | null;
    }>;
    markVoiceSent(id: string, userId?: string, userRole?: UserRole): Promise<{
        status: import("@ilona/database").$Enums.LessonStatus;
        groupId: string;
        teacherId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        duration: number;
        description: string | null;
        topic: string | null;
        creationSource: import("@ilona/database").$Enums.LessonCreationSource;
        substituteTeacherId: string | null;
        scheduledAt: Date;
        vocabularySent: boolean;
        vocabularySentAt: Date | null;
        feedbacksCompleted: boolean;
        feedbacksCompletedAt: Date | null;
        absenceMarked: boolean;
        absenceMarkedAt: Date | null;
        voiceSent: boolean;
        voiceSentAt: Date | null;
        textSent: boolean;
        textSentAt: Date | null;
        completedAt: Date | null;
    }>;
    markTextSent(id: string, userId?: string, userRole?: UserRole): Promise<{
        status: import("@ilona/database").$Enums.LessonStatus;
        groupId: string;
        teacherId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        duration: number;
        description: string | null;
        topic: string | null;
        creationSource: import("@ilona/database").$Enums.LessonCreationSource;
        substituteTeacherId: string | null;
        scheduledAt: Date;
        vocabularySent: boolean;
        vocabularySentAt: Date | null;
        feedbacksCompleted: boolean;
        feedbacksCompletedAt: Date | null;
        absenceMarked: boolean;
        absenceMarkedAt: Date | null;
        voiceSent: boolean;
        voiceSentAt: Date | null;
        textSent: boolean;
        textSentAt: Date | null;
        completedAt: Date | null;
    }>;
    createRecurring(params: {
        groupId: string;
        teacherId: string;
        weekdays: number[];
        startTime: string;
        endTime: string;
        startDate: Date;
        endDate: Date;
        topic?: string;
        description?: string;
    }): Promise<unknown>;
    getLessonStatistics(teacherId?: string, dateFrom?: Date, dateTo?: Date, centerId?: string): Promise<{
        total: number;
        completed: number;
        cancelled: number;
        missed: number;
        inProgress: number;
        scheduled: number;
        completionRate: number;
    }>;
}
