/** Local landing assets — do not use remote Figma URLs in UI */
export const LANDING_ASSETS = {
  heroPerson: '/landing/hero-person.webp',
  heroUkBadge: '/landing/hero-uk-badge.webp',
  heroUsBadge: '/landing/hero-us-badge.webp',
  aboutBigBen: '/landing/about-big-ben.webp',
  aboutFlag: '/landing/about-flag.webp',
  aboutSuccessIcon: '/landing/about-success-icon.webp',
  aboutBranchesIcon: '/landing/about-branches-icon.webp',
  whyMethods: '/landing/why-methods.webp',
  whyResults: '/landing/why-results.webp',
  whyTeachers: '/landing/why-teachers.webp',
  whySchedule: '/landing/why-schedule.webp',
  whyPlatform: '/landing/why-platform-premium.webp',
  studentSuccess: '/landing/student-success.webp',
  registerArrow: '/register-arrow.webp',
  registerSubmitIcon: '/landing/register-submit-icon.webp',
  branchNavArrow: '/landing/branch-nav-arrow.webp',
  teamCheckIcon: '/landing/team-check-icon.webp',
  newsImage1: '/landing/news-image-1.webp',
  newsImage1Overlay: '/landing/news-image-1-overlay.webp',
  newsImage2: '/landing/news-image-2.webp',
  newsImage2Overlay: '/landing/news-image-2-overlay.webp',
  newsImage3: '/landing/news-image-3.webp',
  newsImage3Overlay: '/landing/news-image-3-overlay.webp',
  newsArrowIcon: '/landing/news-arrow-icon.webp',
  faqDropdownIcon: '/landing/faq-dropdown-icon.webp',
  footerLogo: '/landing/footer-logo.webp',
  footerFlagUsa: '/landing/footer-flag-usa.webp',
  footerFlagUk: '/landing/footer-flag-uk.webp',
} as const;
