import { PrismaService } from '../prisma/prisma.service';
import { Prisma } from '@ilona/database';
import { CreatePaymentDto, UpdatePaymentDto, ProcessPaymentDto } from './dto/create-payment.dto';
import { PaymentQueryService } from './payment-query.service';
export declare class PaymentWriteService {
    private readonly prisma;
    private readonly queryService;
    constructor(prisma: PrismaService, queryService: PaymentQueryService);
    private get db();
    create(dto: CreatePaymentDto): Promise<{
        student: {
            user: {
                status: import("@ilona/database").$Enums.UserStatus;
                role: import("@ilona/database").$Enums.UserRole;
                id: string;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                phone: string | null;
                avatarUrl: string | null;
                lastLoginAt: Date | null;
                lastSeenAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
            };
            center: {
                name: string;
                id: string;
                email: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                address: string | null;
                description: string | null;
                colorHex: string | null;
                isActive: boolean;
            } | null;
            group: {
                name: string;
                centerId: string;
                teacherId: string | null;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                description: string | null;
                isActive: boolean;
                iconKey: string | null;
                level: string | null;
                maxStudents: number;
                secondTeacherId: string | null;
                secondTeacherStartsFirstWeek: boolean;
                schedule: Prisma.JsonValue | null;
            } | null;
            teacher: {
                id: string;
                userId: string;
                createdAt: Date;
                updatedAt: Date;
                bio: string | null;
                specialization: string | null;
                hourlyRate: Prisma.Decimal;
                lessonRateAMD: Prisma.Decimal | null;
                videoUrl: string | null;
                workingDays: string[];
                workingHours: Prisma.JsonValue | null;
                hireDate: Date | null;
            } | null;
            _count: {
                attendances: number;
                feedbacks: number;
                payments: number;
                group: number;
                center: number;
                lead: number;
                teacher: number;
                user: number;
                groupHistory: number;
                plannedAbsences: number;
                recordingItems: number;
                notesList: number;
            };
            feedbacks: {
                teacherId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                lessonId: string;
                studentId: string;
                level: import("@ilona/database").$Enums.CefrLevel | null;
                rating: number | null;
                strengths: string | null;
                improvements: string | null;
                grammarTopics: string[];
                skills: string[];
                skillsNote: string | null;
                participation: number | null;
                progress: string | null;
                encouragement: string | null;
            }[];
            attendances: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                lessonId: string;
                studentId: string;
                markedById: string | null;
                isPresent: boolean;
                absenceType: import("@ilona/database").$Enums.AbsenceType | null;
                note: string | null;
                markedAt: Date;
            }[];
            payments: {
                status: import("@ilona/database").$Enums.PaymentStatus;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                notes: string | null;
                studentId: string;
                month: Date;
                transactionId: string | null;
                amount: Prisma.Decimal;
                paidAt: Date | null;
                dueDate: Date;
                paymentMethod: string | null;
                receiptUrl: string | null;
            }[];
            lead: {
                status: import("@ilona/database").$Enums.CrmLeadStatus;
                groupId: string | null;
                centerId: string | null;
                teacherId: string | null;
                id: string;
                firstName: string | null;
                lastName: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                createdByUserId: string;
                assignedManagerId: string | null;
                age: number | null;
                dateOfBirth: Date | null;
                parentName: string | null;
                parentPhone: string | null;
                parentEmail: string | null;
                parentPassportInfo: string | null;
                firstLessonDate: Date | null;
                comment: string | null;
                levelId: string | null;
                transferFlag: boolean;
                transferComment: string | null;
                archivedReason: string | null;
                source: string | null;
                notes: string | null;
                teacherApprovedAt: Date | null;
            } | null;
            groupHistory: {
                groupId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                joinedAt: Date;
                leftAt: Date | null;
                studentId: string;
            }[];
            plannedAbsences: {
                status: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                comment: string;
                studentId: string;
                date: Date;
            }[];
            recordingItems: {
                groupId: string;
                id: string;
                createdAt: Date;
                fileUrl: string;
                fileName: string | null;
                lessonId: string | null;
                studentId: string;
                durationSec: number | null;
                recordedAt: Date;
            }[];
            notesList: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                studentId: string;
            }[];
        } & {
            status: import("@ilona/database").$Enums.StudentStatus;
            groupId: string | null;
            centerId: string | null;
            teacherId: string | null;
            id: string;
            userId: string;
            createdAt: Date;
            updatedAt: Date;
            age: number | null;
            dateOfBirth: Date | null;
            parentName: string | null;
            parentPhone: string | null;
            parentEmail: string | null;
            parentPassportInfo: string | null;
            firstLessonDate: Date | null;
            notes: string | null;
            currentStreak: number;
            riskLabel: import("@ilona/database").$Enums.RiskLabel;
            monthlyFee: Prisma.Decimal;
            enrolledAt: Date;
            registerDate: Date | null;
            receiveReports: boolean;
            leadId: string | null;
        };
    } & {
        status: import("@ilona/database").$Enums.PaymentStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        studentId: string;
        month: Date;
        transactionId: string | null;
        amount: Prisma.Decimal;
        paidAt: Date | null;
        dueDate: Date;
        paymentMethod: string | null;
        receiptUrl: string | null;
    }>;
    update(id: string, dto: UpdatePaymentDto): Promise<{
        student: {
            user: {
                status: import("@ilona/database").$Enums.UserStatus;
                role: import("@ilona/database").$Enums.UserRole;
                id: string;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                phone: string | null;
                avatarUrl: string | null;
                lastLoginAt: Date | null;
                lastSeenAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
            };
            center: {
                name: string;
                id: string;
                email: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                address: string | null;
                description: string | null;
                colorHex: string | null;
                isActive: boolean;
            } | null;
            group: {
                name: string;
                centerId: string;
                teacherId: string | null;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                description: string | null;
                isActive: boolean;
                iconKey: string | null;
                level: string | null;
                maxStudents: number;
                secondTeacherId: string | null;
                secondTeacherStartsFirstWeek: boolean;
                schedule: Prisma.JsonValue | null;
            } | null;
            teacher: {
                id: string;
                userId: string;
                createdAt: Date;
                updatedAt: Date;
                bio: string | null;
                specialization: string | null;
                hourlyRate: Prisma.Decimal;
                lessonRateAMD: Prisma.Decimal | null;
                videoUrl: string | null;
                workingDays: string[];
                workingHours: Prisma.JsonValue | null;
                hireDate: Date | null;
            } | null;
            _count: {
                attendances: number;
                feedbacks: number;
                payments: number;
                group: number;
                center: number;
                lead: number;
                teacher: number;
                user: number;
                groupHistory: number;
                plannedAbsences: number;
                recordingItems: number;
                notesList: number;
            };
            feedbacks: {
                teacherId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                lessonId: string;
                studentId: string;
                level: import("@ilona/database").$Enums.CefrLevel | null;
                rating: number | null;
                strengths: string | null;
                improvements: string | null;
                grammarTopics: string[];
                skills: string[];
                skillsNote: string | null;
                participation: number | null;
                progress: string | null;
                encouragement: string | null;
            }[];
            attendances: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                lessonId: string;
                studentId: string;
                markedById: string | null;
                isPresent: boolean;
                absenceType: import("@ilona/database").$Enums.AbsenceType | null;
                note: string | null;
                markedAt: Date;
            }[];
            payments: {
                status: import("@ilona/database").$Enums.PaymentStatus;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                notes: string | null;
                studentId: string;
                month: Date;
                transactionId: string | null;
                amount: Prisma.Decimal;
                paidAt: Date | null;
                dueDate: Date;
                paymentMethod: string | null;
                receiptUrl: string | null;
            }[];
            lead: {
                status: import("@ilona/database").$Enums.CrmLeadStatus;
                groupId: string | null;
                centerId: string | null;
                teacherId: string | null;
                id: string;
                firstName: string | null;
                lastName: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                createdByUserId: string;
                assignedManagerId: string | null;
                age: number | null;
                dateOfBirth: Date | null;
                parentName: string | null;
                parentPhone: string | null;
                parentEmail: string | null;
                parentPassportInfo: string | null;
                firstLessonDate: Date | null;
                comment: string | null;
                levelId: string | null;
                transferFlag: boolean;
                transferComment: string | null;
                archivedReason: string | null;
                source: string | null;
                notes: string | null;
                teacherApprovedAt: Date | null;
            } | null;
            groupHistory: {
                groupId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                joinedAt: Date;
                leftAt: Date | null;
                studentId: string;
            }[];
            plannedAbsences: {
                status: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                comment: string;
                studentId: string;
                date: Date;
            }[];
            recordingItems: {
                groupId: string;
                id: string;
                createdAt: Date;
                fileUrl: string;
                fileName: string | null;
                lessonId: string | null;
                studentId: string;
                durationSec: number | null;
                recordedAt: Date;
            }[];
            notesList: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                studentId: string;
            }[];
        } & {
            status: import("@ilona/database").$Enums.StudentStatus;
            groupId: string | null;
            centerId: string | null;
            teacherId: string | null;
            id: string;
            userId: string;
            createdAt: Date;
            updatedAt: Date;
            age: number | null;
            dateOfBirth: Date | null;
            parentName: string | null;
            parentPhone: string | null;
            parentEmail: string | null;
            parentPassportInfo: string | null;
            firstLessonDate: Date | null;
            notes: string | null;
            currentStreak: number;
            riskLabel: import("@ilona/database").$Enums.RiskLabel;
            monthlyFee: Prisma.Decimal;
            enrolledAt: Date;
            registerDate: Date | null;
            receiveReports: boolean;
            leadId: string | null;
        };
    } & {
        status: import("@ilona/database").$Enums.PaymentStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        studentId: string;
        month: Date;
        transactionId: string | null;
        amount: Prisma.Decimal;
        paidAt: Date | null;
        dueDate: Date;
        paymentMethod: string | null;
        receiptUrl: string | null;
    }>;
    processPayment(id: string, dto: ProcessPaymentDto): Promise<{
        student: {
            user: {
                status: import("@ilona/database").$Enums.UserStatus;
                role: import("@ilona/database").$Enums.UserRole;
                id: string;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                phone: string | null;
                avatarUrl: string | null;
                lastLoginAt: Date | null;
                lastSeenAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
            };
            center: {
                name: string;
                id: string;
                email: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                address: string | null;
                description: string | null;
                colorHex: string | null;
                isActive: boolean;
            } | null;
            group: {
                name: string;
                centerId: string;
                teacherId: string | null;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                description: string | null;
                isActive: boolean;
                iconKey: string | null;
                level: string | null;
                maxStudents: number;
                secondTeacherId: string | null;
                secondTeacherStartsFirstWeek: boolean;
                schedule: Prisma.JsonValue | null;
            } | null;
            teacher: {
                id: string;
                userId: string;
                createdAt: Date;
                updatedAt: Date;
                bio: string | null;
                specialization: string | null;
                hourlyRate: Prisma.Decimal;
                lessonRateAMD: Prisma.Decimal | null;
                videoUrl: string | null;
                workingDays: string[];
                workingHours: Prisma.JsonValue | null;
                hireDate: Date | null;
            } | null;
            _count: {
                attendances: number;
                feedbacks: number;
                payments: number;
                group: number;
                center: number;
                lead: number;
                teacher: number;
                user: number;
                groupHistory: number;
                plannedAbsences: number;
                recordingItems: number;
                notesList: number;
            };
            feedbacks: {
                teacherId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                lessonId: string;
                studentId: string;
                level: import("@ilona/database").$Enums.CefrLevel | null;
                rating: number | null;
                strengths: string | null;
                improvements: string | null;
                grammarTopics: string[];
                skills: string[];
                skillsNote: string | null;
                participation: number | null;
                progress: string | null;
                encouragement: string | null;
            }[];
            attendances: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                lessonId: string;
                studentId: string;
                markedById: string | null;
                isPresent: boolean;
                absenceType: import("@ilona/database").$Enums.AbsenceType | null;
                note: string | null;
                markedAt: Date;
            }[];
            payments: {
                status: import("@ilona/database").$Enums.PaymentStatus;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                notes: string | null;
                studentId: string;
                month: Date;
                transactionId: string | null;
                amount: Prisma.Decimal;
                paidAt: Date | null;
                dueDate: Date;
                paymentMethod: string | null;
                receiptUrl: string | null;
            }[];
            lead: {
                status: import("@ilona/database").$Enums.CrmLeadStatus;
                groupId: string | null;
                centerId: string | null;
                teacherId: string | null;
                id: string;
                firstName: string | null;
                lastName: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                createdByUserId: string;
                assignedManagerId: string | null;
                age: number | null;
                dateOfBirth: Date | null;
                parentName: string | null;
                parentPhone: string | null;
                parentEmail: string | null;
                parentPassportInfo: string | null;
                firstLessonDate: Date | null;
                comment: string | null;
                levelId: string | null;
                transferFlag: boolean;
                transferComment: string | null;
                archivedReason: string | null;
                source: string | null;
                notes: string | null;
                teacherApprovedAt: Date | null;
            } | null;
            groupHistory: {
                groupId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                joinedAt: Date;
                leftAt: Date | null;
                studentId: string;
            }[];
            plannedAbsences: {
                status: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                comment: string;
                studentId: string;
                date: Date;
            }[];
            recordingItems: {
                groupId: string;
                id: string;
                createdAt: Date;
                fileUrl: string;
                fileName: string | null;
                lessonId: string | null;
                studentId: string;
                durationSec: number | null;
                recordedAt: Date;
            }[];
            notesList: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                studentId: string;
            }[];
        } & {
            status: import("@ilona/database").$Enums.StudentStatus;
            groupId: string | null;
            centerId: string | null;
            teacherId: string | null;
            id: string;
            userId: string;
            createdAt: Date;
            updatedAt: Date;
            age: number | null;
            dateOfBirth: Date | null;
            parentName: string | null;
            parentPhone: string | null;
            parentEmail: string | null;
            parentPassportInfo: string | null;
            firstLessonDate: Date | null;
            notes: string | null;
            currentStreak: number;
            riskLabel: import("@ilona/database").$Enums.RiskLabel;
            monthlyFee: Prisma.Decimal;
            enrolledAt: Date;
            registerDate: Date | null;
            receiveReports: boolean;
            leadId: string | null;
        };
    } & {
        status: import("@ilona/database").$Enums.PaymentStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        studentId: string;
        month: Date;
        transactionId: string | null;
        amount: Prisma.Decimal;
        paidAt: Date | null;
        dueDate: Date;
        paymentMethod: string | null;
        receiptUrl: string | null;
    }>;
    processPaymentForStudent(paymentId: string, studentId: string, dto: ProcessPaymentDto): Promise<{
        student: {
            user: {
                status: import("@ilona/database").$Enums.UserStatus;
                role: import("@ilona/database").$Enums.UserRole;
                id: string;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                phone: string | null;
                avatarUrl: string | null;
                lastLoginAt: Date | null;
                lastSeenAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
            };
            center: {
                name: string;
                id: string;
                email: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                address: string | null;
                description: string | null;
                colorHex: string | null;
                isActive: boolean;
            } | null;
            group: {
                name: string;
                centerId: string;
                teacherId: string | null;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                description: string | null;
                isActive: boolean;
                iconKey: string | null;
                level: string | null;
                maxStudents: number;
                secondTeacherId: string | null;
                secondTeacherStartsFirstWeek: boolean;
                schedule: Prisma.JsonValue | null;
            } | null;
            teacher: {
                id: string;
                userId: string;
                createdAt: Date;
                updatedAt: Date;
                bio: string | null;
                specialization: string | null;
                hourlyRate: Prisma.Decimal;
                lessonRateAMD: Prisma.Decimal | null;
                videoUrl: string | null;
                workingDays: string[];
                workingHours: Prisma.JsonValue | null;
                hireDate: Date | null;
            } | null;
            _count: {
                attendances: number;
                feedbacks: number;
                payments: number;
                group: number;
                center: number;
                lead: number;
                teacher: number;
                user: number;
                groupHistory: number;
                plannedAbsences: number;
                recordingItems: number;
                notesList: number;
            };
            feedbacks: {
                teacherId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                lessonId: string;
                studentId: string;
                level: import("@ilona/database").$Enums.CefrLevel | null;
                rating: number | null;
                strengths: string | null;
                improvements: string | null;
                grammarTopics: string[];
                skills: string[];
                skillsNote: string | null;
                participation: number | null;
                progress: string | null;
                encouragement: string | null;
            }[];
            attendances: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                lessonId: string;
                studentId: string;
                markedById: string | null;
                isPresent: boolean;
                absenceType: import("@ilona/database").$Enums.AbsenceType | null;
                note: string | null;
                markedAt: Date;
            }[];
            payments: {
                status: import("@ilona/database").$Enums.PaymentStatus;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                notes: string | null;
                studentId: string;
                month: Date;
                transactionId: string | null;
                amount: Prisma.Decimal;
                paidAt: Date | null;
                dueDate: Date;
                paymentMethod: string | null;
                receiptUrl: string | null;
            }[];
            lead: {
                status: import("@ilona/database").$Enums.CrmLeadStatus;
                groupId: string | null;
                centerId: string | null;
                teacherId: string | null;
                id: string;
                firstName: string | null;
                lastName: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                createdByUserId: string;
                assignedManagerId: string | null;
                age: number | null;
                dateOfBirth: Date | null;
                parentName: string | null;
                parentPhone: string | null;
                parentEmail: string | null;
                parentPassportInfo: string | null;
                firstLessonDate: Date | null;
                comment: string | null;
                levelId: string | null;
                transferFlag: boolean;
                transferComment: string | null;
                archivedReason: string | null;
                source: string | null;
                notes: string | null;
                teacherApprovedAt: Date | null;
            } | null;
            groupHistory: {
                groupId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                joinedAt: Date;
                leftAt: Date | null;
                studentId: string;
            }[];
            plannedAbsences: {
                status: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                comment: string;
                studentId: string;
                date: Date;
            }[];
            recordingItems: {
                groupId: string;
                id: string;
                createdAt: Date;
                fileUrl: string;
                fileName: string | null;
                lessonId: string | null;
                studentId: string;
                durationSec: number | null;
                recordedAt: Date;
            }[];
            notesList: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                studentId: string;
            }[];
        } & {
            status: import("@ilona/database").$Enums.StudentStatus;
            groupId: string | null;
            centerId: string | null;
            teacherId: string | null;
            id: string;
            userId: string;
            createdAt: Date;
            updatedAt: Date;
            age: number | null;
            dateOfBirth: Date | null;
            parentName: string | null;
            parentPhone: string | null;
            parentEmail: string | null;
            parentPassportInfo: string | null;
            firstLessonDate: Date | null;
            notes: string | null;
            currentStreak: number;
            riskLabel: import("@ilona/database").$Enums.RiskLabel;
            monthlyFee: Prisma.Decimal;
            enrolledAt: Date;
            registerDate: Date | null;
            receiveReports: boolean;
            leadId: string | null;
        };
    } & {
        status: import("@ilona/database").$Enums.PaymentStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        studentId: string;
        month: Date;
        transactionId: string | null;
        amount: Prisma.Decimal;
        paidAt: Date | null;
        dueDate: Date;
        paymentMethod: string | null;
        receiptUrl: string | null;
    }>;
    cancel(id: string): Promise<{
        status: import("@ilona/database").$Enums.PaymentStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        studentId: string;
        month: Date;
        transactionId: string | null;
        amount: Prisma.Decimal;
        paidAt: Date | null;
        dueDate: Date;
        paymentMethod: string | null;
        receiptUrl: string | null;
    }>;
    delete(id: string): Promise<{
        status: import("@ilona/database").$Enums.PaymentStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        studentId: string;
        month: Date;
        transactionId: string | null;
        amount: Prisma.Decimal;
        paidAt: Date | null;
        dueDate: Date;
        paymentMethod: string | null;
        receiptUrl: string | null;
    }>;
    deleteMany(ids: string[]): Promise<{
        deleted: number;
    }>;
}
