import { PrismaService } from '../prisma/prisma.service';
import { Prisma, PaymentStatus } from '@ilona/database';
export declare class PaymentQueryService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    private get db();
    findAll(params?: {
        skip?: number;
        take?: number;
        studentId?: string;
        status?: PaymentStatus;
        dateFrom?: Date;
        dateTo?: Date;
        q?: string;
        centerId?: string;
    }): Promise<{
        items: ({
            student: {
                user: {
                    status: import("@ilona/database").$Enums.UserStatus;
                    role: import("@ilona/database").$Enums.UserRole;
                    id: string;
                    email: string;
                    passwordHash: string;
                    firstName: string;
                    lastName: string;
                    phone: string | null;
                    avatarUrl: string | null;
                    lastLoginAt: Date | null;
                    lastSeenAt: Date | null;
                    createdAt: Date;
                    updatedAt: Date;
                };
                center: {
                    name: string;
                    id: string;
                    email: string | null;
                    phone: string | null;
                    createdAt: Date;
                    updatedAt: Date;
                    address: string | null;
                    description: string | null;
                    colorHex: string | null;
                    isActive: boolean;
                } | null;
                group: {
                    name: string;
                    centerId: string;
                    teacherId: string | null;
                    id: string;
                    createdAt: Date;
                    updatedAt: Date;
                    description: string | null;
                    isActive: boolean;
                    iconKey: string | null;
                    level: string | null;
                    maxStudents: number;
                    secondTeacherId: string | null;
                    secondTeacherStartsFirstWeek: boolean;
                    schedule: Prisma.JsonValue | null;
                } | null;
                teacher: {
                    id: string;
                    userId: string;
                    createdAt: Date;
                    updatedAt: Date;
                    bio: string | null;
                    specialization: string | null;
                    hourlyRate: Prisma.Decimal;
                    lessonRateAMD: Prisma.Decimal | null;
                    videoUrl: string | null;
                    workingDays: string[];
                    workingHours: Prisma.JsonValue | null;
                    hireDate: Date | null;
                } | null;
                _count: {
                    attendances: number;
                    feedbacks: number;
                    payments: number;
                    group: number;
                    center: number;
                    lead: number;
                    teacher: number;
                    user: number;
                    groupHistory: number;
                    plannedAbsences: number;
                    recordingItems: number;
                    notesList: number;
                };
                feedbacks: {
                    teacherId: string;
                    id: string;
                    createdAt: Date;
                    updatedAt: Date;
                    content: string;
                    lessonId: string;
                    studentId: string;
                    level: import("@ilona/database").$Enums.CefrLevel | null;
                    rating: number | null;
                    strengths: string | null;
                    improvements: string | null;
                    grammarTopics: string[];
                    skills: string[];
                    skillsNote: string | null;
                    participation: number | null;
                    progress: string | null;
                    encouragement: string | null;
                }[];
                attendances: {
                    id: string;
                    createdAt: Date;
                    updatedAt: Date;
                    lessonId: string;
                    studentId: string;
                    markedById: string | null;
                    isPresent: boolean;
                    absenceType: import("@ilona/database").$Enums.AbsenceType | null;
                    note: string | null;
                    markedAt: Date;
                }[];
                payments: {
                    status: import("@ilona/database").$Enums.PaymentStatus;
                    id: string;
                    createdAt: Date;
                    updatedAt: Date;
                    notes: string | null;
                    studentId: string;
                    month: Date;
                    transactionId: string | null;
                    amount: Prisma.Decimal;
                    paidAt: Date | null;
                    dueDate: Date;
                    paymentMethod: string | null;
                    receiptUrl: string | null;
                }[];
                lead: {
                    status: import("@ilona/database").$Enums.CrmLeadStatus;
                    groupId: string | null;
                    centerId: string | null;
                    teacherId: string | null;
                    id: string;
                    firstName: string | null;
                    lastName: string | null;
                    phone: string | null;
                    createdAt: Date;
                    updatedAt: Date;
                    createdByUserId: string;
                    assignedManagerId: string | null;
                    age: number | null;
                    dateOfBirth: Date | null;
                    parentName: string | null;
                    parentPhone: string | null;
                    parentEmail: string | null;
                    parentPassportInfo: string | null;
                    firstLessonDate: Date | null;
                    comment: string | null;
                    levelId: string | null;
                    transferFlag: boolean;
                    transferComment: string | null;
                    archivedReason: string | null;
                    source: string | null;
                    notes: string | null;
                    teacherApprovedAt: Date | null;
                } | null;
                groupHistory: {
                    groupId: string;
                    id: string;
                    createdAt: Date;
                    updatedAt: Date;
                    joinedAt: Date;
                    leftAt: Date | null;
                    studentId: string;
                }[];
                plannedAbsences: {
                    status: string;
                    id: string;
                    createdAt: Date;
                    updatedAt: Date;
                    comment: string;
                    studentId: string;
                    date: Date;
                }[];
                recordingItems: {
                    groupId: string;
                    id: string;
                    createdAt: Date;
                    fileUrl: string;
                    fileName: string | null;
                    lessonId: string | null;
                    studentId: string;
                    durationSec: number | null;
                    recordedAt: Date;
                }[];
                notesList: {
                    id: string;
                    createdAt: Date;
                    updatedAt: Date;
                    content: string;
                    studentId: string;
                }[];
            } & {
                status: import("@ilona/database").$Enums.StudentStatus;
                groupId: string | null;
                centerId: string | null;
                teacherId: string | null;
                id: string;
                userId: string;
                createdAt: Date;
                updatedAt: Date;
                age: number | null;
                dateOfBirth: Date | null;
                parentName: string | null;
                parentPhone: string | null;
                parentEmail: string | null;
                parentPassportInfo: string | null;
                firstLessonDate: Date | null;
                notes: string | null;
                currentStreak: number;
                riskLabel: import("@ilona/database").$Enums.RiskLabel;
                monthlyFee: Prisma.Decimal;
                enrolledAt: Date;
                registerDate: Date | null;
                receiveReports: boolean;
                leadId: string | null;
            };
        } & {
            status: import("@ilona/database").$Enums.PaymentStatus;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            notes: string | null;
            studentId: string;
            month: Date;
            transactionId: string | null;
            amount: Prisma.Decimal;
            paidAt: Date | null;
            dueDate: Date;
            paymentMethod: string | null;
            receiptUrl: string | null;
        })[];
        total: number;
        page: number;
        pageSize: number;
        totalPages: number;
    }>;
    findMonthlyGroupedForStudent(params: {
        studentId: string;
        skip?: number;
        take?: number;
        status?: PaymentStatus;
        dateFrom?: Date;
        dateTo?: Date;
    }): Promise<{
        items: {
            id: string;
            studentId: string;
            amount: number;
            status: "PAID" | "PENDING" | "OVERDUE";
            dueDate: Date;
            month: Date;
            paidAt: Date | null;
            paymentMethod: string | null;
            transactionId: string | null;
            receiptUrl: string | null;
            notes: string | null;
            createdAt: Date;
            updatedAt: Date;
            student: {
                user: {
                    email: string;
                    firstName: string;
                    lastName: string;
                };
                group: {
                    name: string;
                    id: string;
                } | null;
            } & {
                status: import("@ilona/database").$Enums.StudentStatus;
                groupId: string | null;
                centerId: string | null;
                teacherId: string | null;
                id: string;
                userId: string;
                createdAt: Date;
                updatedAt: Date;
                age: number | null;
                dateOfBirth: Date | null;
                parentName: string | null;
                parentPhone: string | null;
                parentEmail: string | null;
                parentPassportInfo: string | null;
                firstLessonDate: Date | null;
                notes: string | null;
                currentStreak: number;
                riskLabel: import("@ilona/database").$Enums.RiskLabel;
                monthlyFee: Prisma.Decimal;
                enrolledAt: Date;
                registerDate: Date | null;
                receiveReports: boolean;
                leadId: string | null;
            };
            canPay: boolean;
            paymentWindowReason: import("./payment.util").PaymentWindowReason | undefined;
        }[];
        total: number;
        page: number;
        pageSize: number;
        totalPages: number;
    }>;
    findById(id: string): Promise<{
        student: {
            user: {
                status: import("@ilona/database").$Enums.UserStatus;
                role: import("@ilona/database").$Enums.UserRole;
                id: string;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                phone: string | null;
                avatarUrl: string | null;
                lastLoginAt: Date | null;
                lastSeenAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
            };
            center: {
                name: string;
                id: string;
                email: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                address: string | null;
                description: string | null;
                colorHex: string | null;
                isActive: boolean;
            } | null;
            group: {
                name: string;
                centerId: string;
                teacherId: string | null;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                description: string | null;
                isActive: boolean;
                iconKey: string | null;
                level: string | null;
                maxStudents: number;
                secondTeacherId: string | null;
                secondTeacherStartsFirstWeek: boolean;
                schedule: Prisma.JsonValue | null;
            } | null;
            teacher: {
                id: string;
                userId: string;
                createdAt: Date;
                updatedAt: Date;
                bio: string | null;
                specialization: string | null;
                hourlyRate: Prisma.Decimal;
                lessonRateAMD: Prisma.Decimal | null;
                videoUrl: string | null;
                workingDays: string[];
                workingHours: Prisma.JsonValue | null;
                hireDate: Date | null;
            } | null;
            _count: {
                attendances: number;
                feedbacks: number;
                payments: number;
                group: number;
                center: number;
                lead: number;
                teacher: number;
                user: number;
                groupHistory: number;
                plannedAbsences: number;
                recordingItems: number;
                notesList: number;
            };
            feedbacks: {
                teacherId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                lessonId: string;
                studentId: string;
                level: import("@ilona/database").$Enums.CefrLevel | null;
                rating: number | null;
                strengths: string | null;
                improvements: string | null;
                grammarTopics: string[];
                skills: string[];
                skillsNote: string | null;
                participation: number | null;
                progress: string | null;
                encouragement: string | null;
            }[];
            attendances: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                lessonId: string;
                studentId: string;
                markedById: string | null;
                isPresent: boolean;
                absenceType: import("@ilona/database").$Enums.AbsenceType | null;
                note: string | null;
                markedAt: Date;
            }[];
            payments: {
                status: import("@ilona/database").$Enums.PaymentStatus;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                notes: string | null;
                studentId: string;
                month: Date;
                transactionId: string | null;
                amount: Prisma.Decimal;
                paidAt: Date | null;
                dueDate: Date;
                paymentMethod: string | null;
                receiptUrl: string | null;
            }[];
            lead: {
                status: import("@ilona/database").$Enums.CrmLeadStatus;
                groupId: string | null;
                centerId: string | null;
                teacherId: string | null;
                id: string;
                firstName: string | null;
                lastName: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                createdByUserId: string;
                assignedManagerId: string | null;
                age: number | null;
                dateOfBirth: Date | null;
                parentName: string | null;
                parentPhone: string | null;
                parentEmail: string | null;
                parentPassportInfo: string | null;
                firstLessonDate: Date | null;
                comment: string | null;
                levelId: string | null;
                transferFlag: boolean;
                transferComment: string | null;
                archivedReason: string | null;
                source: string | null;
                notes: string | null;
                teacherApprovedAt: Date | null;
            } | null;
            groupHistory: {
                groupId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                joinedAt: Date;
                leftAt: Date | null;
                studentId: string;
            }[];
            plannedAbsences: {
                status: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                comment: string;
                studentId: string;
                date: Date;
            }[];
            recordingItems: {
                groupId: string;
                id: string;
                createdAt: Date;
                fileUrl: string;
                fileName: string | null;
                lessonId: string | null;
                studentId: string;
                durationSec: number | null;
                recordedAt: Date;
            }[];
            notesList: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                studentId: string;
            }[];
        } & {
            status: import("@ilona/database").$Enums.StudentStatus;
            groupId: string | null;
            centerId: string | null;
            teacherId: string | null;
            id: string;
            userId: string;
            createdAt: Date;
            updatedAt: Date;
            age: number | null;
            dateOfBirth: Date | null;
            parentName: string | null;
            parentPhone: string | null;
            parentEmail: string | null;
            parentPassportInfo: string | null;
            firstLessonDate: Date | null;
            notes: string | null;
            currentStreak: number;
            riskLabel: import("@ilona/database").$Enums.RiskLabel;
            monthlyFee: Prisma.Decimal;
            enrolledAt: Date;
            registerDate: Date | null;
            receiveReports: boolean;
            leadId: string | null;
        };
    } & {
        status: import("@ilona/database").$Enums.PaymentStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        studentId: string;
        month: Date;
        transactionId: string | null;
        amount: Prisma.Decimal;
        paidAt: Date | null;
        dueDate: Date;
        paymentMethod: string | null;
        receiptUrl: string | null;
    }>;
    findByIdAndStudentId(paymentId: string, studentId: string): Promise<({
        student: {
            user: {
                status: import("@ilona/database").$Enums.UserStatus;
                role: import("@ilona/database").$Enums.UserRole;
                id: string;
                email: string;
                passwordHash: string;
                firstName: string;
                lastName: string;
                phone: string | null;
                avatarUrl: string | null;
                lastLoginAt: Date | null;
                lastSeenAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
            };
            center: {
                name: string;
                id: string;
                email: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                address: string | null;
                description: string | null;
                colorHex: string | null;
                isActive: boolean;
            } | null;
            group: {
                name: string;
                centerId: string;
                teacherId: string | null;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                description: string | null;
                isActive: boolean;
                iconKey: string | null;
                level: string | null;
                maxStudents: number;
                secondTeacherId: string | null;
                secondTeacherStartsFirstWeek: boolean;
                schedule: Prisma.JsonValue | null;
            } | null;
            teacher: {
                id: string;
                userId: string;
                createdAt: Date;
                updatedAt: Date;
                bio: string | null;
                specialization: string | null;
                hourlyRate: Prisma.Decimal;
                lessonRateAMD: Prisma.Decimal | null;
                videoUrl: string | null;
                workingDays: string[];
                workingHours: Prisma.JsonValue | null;
                hireDate: Date | null;
            } | null;
            _count: {
                attendances: number;
                feedbacks: number;
                payments: number;
                group: number;
                center: number;
                lead: number;
                teacher: number;
                user: number;
                groupHistory: number;
                plannedAbsences: number;
                recordingItems: number;
                notesList: number;
            };
            feedbacks: {
                teacherId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                lessonId: string;
                studentId: string;
                level: import("@ilona/database").$Enums.CefrLevel | null;
                rating: number | null;
                strengths: string | null;
                improvements: string | null;
                grammarTopics: string[];
                skills: string[];
                skillsNote: string | null;
                participation: number | null;
                progress: string | null;
                encouragement: string | null;
            }[];
            attendances: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                lessonId: string;
                studentId: string;
                markedById: string | null;
                isPresent: boolean;
                absenceType: import("@ilona/database").$Enums.AbsenceType | null;
                note: string | null;
                markedAt: Date;
            }[];
            payments: {
                status: import("@ilona/database").$Enums.PaymentStatus;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                notes: string | null;
                studentId: string;
                month: Date;
                transactionId: string | null;
                amount: Prisma.Decimal;
                paidAt: Date | null;
                dueDate: Date;
                paymentMethod: string | null;
                receiptUrl: string | null;
            }[];
            lead: {
                status: import("@ilona/database").$Enums.CrmLeadStatus;
                groupId: string | null;
                centerId: string | null;
                teacherId: string | null;
                id: string;
                firstName: string | null;
                lastName: string | null;
                phone: string | null;
                createdAt: Date;
                updatedAt: Date;
                createdByUserId: string;
                assignedManagerId: string | null;
                age: number | null;
                dateOfBirth: Date | null;
                parentName: string | null;
                parentPhone: string | null;
                parentEmail: string | null;
                parentPassportInfo: string | null;
                firstLessonDate: Date | null;
                comment: string | null;
                levelId: string | null;
                transferFlag: boolean;
                transferComment: string | null;
                archivedReason: string | null;
                source: string | null;
                notes: string | null;
                teacherApprovedAt: Date | null;
            } | null;
            groupHistory: {
                groupId: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                joinedAt: Date;
                leftAt: Date | null;
                studentId: string;
            }[];
            plannedAbsences: {
                status: string;
                id: string;
                createdAt: Date;
                updatedAt: Date;
                comment: string;
                studentId: string;
                date: Date;
            }[];
            recordingItems: {
                groupId: string;
                id: string;
                createdAt: Date;
                fileUrl: string;
                fileName: string | null;
                lessonId: string | null;
                studentId: string;
                durationSec: number | null;
                recordedAt: Date;
            }[];
            notesList: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                content: string;
                studentId: string;
            }[];
        } & {
            status: import("@ilona/database").$Enums.StudentStatus;
            groupId: string | null;
            centerId: string | null;
            teacherId: string | null;
            id: string;
            userId: string;
            createdAt: Date;
            updatedAt: Date;
            age: number | null;
            dateOfBirth: Date | null;
            parentName: string | null;
            parentPhone: string | null;
            parentEmail: string | null;
            parentPassportInfo: string | null;
            firstLessonDate: Date | null;
            notes: string | null;
            currentStreak: number;
            riskLabel: import("@ilona/database").$Enums.RiskLabel;
            monthlyFee: Prisma.Decimal;
            enrolledAt: Date;
            registerDate: Date | null;
            receiveReports: boolean;
            leadId: string | null;
        };
    } & {
        status: import("@ilona/database").$Enums.PaymentStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        notes: string | null;
        studentId: string;
        month: Date;
        transactionId: string | null;
        amount: Prisma.Decimal;
        paidAt: Date | null;
        dueDate: Date;
        paymentMethod: string | null;
        receiptUrl: string | null;
    }) | null>;
}
